import type { Metadata } from "next";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Inter } from "next/font/google";
import "./globals.css";
import toast, { Toaster } from 'react-hot-toast';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="523889556907-qssuuaiv39r943edi7hqsqiv1g866h8j.apps.googleusercontent.com">
        <body className={inter.className}>{children}</body>
        <Toaster/>
      </GoogleOAuthProvider>
    </html>
  );
}
